export const countries = [
    { code: 'aus', name: 'Australia' },
    { code: 'aut', name: 'Austria' },
    { code: 'bel', name: 'Belgium' },
    { code: 'blr', name: 'Belarus' },
    { code: 'can', name: 'Canada' },
    { code: 'chn', name: 'China' },
    { code: 'cze', name: 'Czech Republic' },
    { code: 'fin', name: 'Finland' },
    { code: 'fra', name: 'France' },
    { code: 'gb', name: 'Great Britain' },
    { code: 'ger', name: 'Germany' },
    { code: 'hun', name: 'Hungary' },
    { code: 'ita', name: 'Italy' },
    { code: 'jpn', name: 'Japan' },
    { code: 'kaz', name: 'Kazakhstan' },
    { code: 'kor', name: 'Korea' },
    { code: 'lat', name: 'Latvia' },
    { code: 'lie', name: 'Liechtenstein' },
    { code: 'ned', name: 'Netherlands' },
    { code: 'nor', name: 'Norway' },
    { code: 'nz', name: 'New Zealand' },
    { code: 'pol', name: 'Poland' },
    { code: 'slo', name: 'Slovenia' },
    { code: 'spa', name: 'Spain' },
    { code: 'svk', name: 'Slovakia' },
    { code: 'swe', name: 'Sweden' },
    { code: 'swi', name: 'Switzerland' },
    { code: 'ukr', name: 'Ukraine' },
    { code: 'us', name: 'United States of America' },
];
